### ISSUE TITLE
IPay interface

### ISSUE THREAD

**Issue by m-jch** [m-jch/ipay#11]
We want create a interface for all port classes, and user payment must be done just by call below methods.

**Notes:**
* ```with``` and ```getRefId``` methods is optional.

```php
<?php

namespace IPay;

interface IPayInterface
{
    /**
     * Initialize class
     *
     * @param Config $config
     * @param DataBaseManager $db
     * @param int $portId
     *
     */
    public function __construct(Config $config, DatabaseManager $db, $portId);

    /**
     * This method use for set price in Rial.
     *
     * @param int $amount in Rial
     *
     * @return $this
     */
    public function set($amount);

    /**
     * Some of the ports can be send additional data to port server.
     * This method for set this additional data.
     *
     * @param array $data
     *
     * @return $this
     */
    public function with(array $data);

    /**
     * This method use for done everything that necessary before redirect to port.
     *
     * @return $this
     */
    public function ready();

    /**
     * Get ref id, in some ports ref id has a different name such as authority
     *
     * @return int|string
     */
    public function refId();

    /**
     * Return tracking code
     *
     * @return int|string
     */
    public function trackingCode();

    /**
     * Get port id, $this->portId
     *
     * @return int
     */
    public function portId();

    /**
     * Get transaction id
     *
     * @return int|null
     */
    public function transactionId();

    /**
     * Return card number
     *
     * @return string
     */
    public function cardNumber();

    /**
     * This method use for redirect to port
     *
     * @return mixed
     */
    public function redirect();

    /**
     * Return result of payment
     * If result is done, return true, otherwise throws an related exception
     *
     * @param object $transaction row of transaction in database
     *
     * @return boolean
     */
    public function verify($transaction);
}
```

If you see a problem or have a new idea please commented in this issue.

**Comment by easteregg** [comment]
You know, this looks pretty good, though in a perfect world, I would like to call something like this: 

Before sending client to gateway: 
```
$myImplementation->set($price)->with($additional_data)->redirect();
```

Client is back, let's verify it. 
```
$myImplementation->verify()->get();
```

So, this way is more readable. and I think we should return $this to leverage method chaining. 

Any thoughts?

**Comment by m-jch** [comment]
Interesting, actually this way is simpler and easier. I think we can't return ```false``` in chaining method, and if any error happen we must throws an exception.

In your example, you define all methods we needs, and i create another Interface for this approach.

Also i think we need a method for get tracking code.

**Comment by m-jch** [comment]
According to @easteregg opinion, I create a new Interface

**Comment by easteregg** [comment]
This looks really good. allow me to play with it for a few days. see if we missed something. I have a ZarrinPal class that could really use a helping hand to refactor. I'm gonna work on it and report it back here. 

thanks @m-jch

**Comment by m-jch** [comment]
Thanks. Also i currently developing Mellat port with this new interface, and if any new problem happen i reported this here.

**Comment by m-jch** [comment]
I Found first problem. For example in Mellat gateway before redirect to port we need to access refId and with methods in last interface we can't do this:

```php
$ipay->set(4000)->redirect();
```

And for this i create new method.

```php
$ipay->set(4000)->ready();
$ipay->redirect();
```

In this way we can access to refId before redirect:

```php
$ipay->set(4000)->ready()->getRefId();
$ipay->redirect();
```

Also i add a new ```getRefId``` method to interface, and update interface in first comment in this issue.

**Comment by m-jch** [comment]
I change and commit IPayMellat class for work with new Interface.

Example of result:

**Redirect to bank**

```php
use IPay\IPay;

$ipay = new IPay(IPay::P_MELLAT);
try {
    $refId = $ipay->set(1000)->ready()->getRefId();
    $ipay->redirect();
} catch (Exception $e) {
    echo $e->getMessage();
}
```

**Verify payment**

```php
use IPay\IPay;

$ipay = new IPay(IPay::P_MELLAT);
try {
    $trackingCode = $ipay->verify()->trackingCode();
} catch (Exception $e) {
    echo $e->getMessage();
}
```

At current, unfortunately, IPayMellat class work with previous version of table, and i still waiting for 
@Reza1607 to complete schema of new table.

**Comment by Reza1607** [comment]
I think,
We need a method to return the bank id.
This method returns the ID of the bank's transactions are in the table we can use it.
~~~php
/**
* return bank id
* @return int
*/
public function getId();
~~~

**Comment by Reza1607** [comment]
The proposed database schema #12 
@m-jch

**Comment by m-jch** [comment]
Interface updated.

```portId``` and ```_construct``` method added.

**Comment by m-jch** [comment]
Interface is updated.
