### ISSUE TITLE
ساختار پیشنهادی برای جداول

### ISSUE THREAD

**Issue by Reza1607** [m-jch/ipay#12]
<div dir="rtl">
ساختار پیشنهادی من به صورت زیر هست که با استفاده از همین جدول میشه درگاه های مختلف رو پوشش داد.
</div>
# Transactions tables

Field Name | Type |Desc   | Default |  PK | Auto Inc.
--- | --- | --- | --- | ---|---
id | int |شماسه تراکنش  |  | * | *
port_id | tinyint(2) | شناسه بانک
price | decimal(15,2)|مبلغ تراکنش
ref_id | varchar(255) | کد ارجاع بانک | null
tracking_code | varchar(50) | کد رهگیری پرداخت | null
status | tinyint(1) | وضعیت پرداخت | 0
payment_date | timestamp | تایم استمپ زمان ثبت پرداخت | null
last_change_date | timestamp | تایم استمپ آخرین تغییر وضعیت پرداخت | null

<div dir="rtl">
برای فیلد وضعیت (**status**) <span dir="rtl">ما می تونید سه نوع وضعیت زیر رو در نظر بگیریم:

0 : تو این وضعیت رکورد تراکنش ثبت شده اما ما هنوز نتیجه ایی از سمت بانک دریافت نکردیم
1 : تو این وضعیت عملیات پرداخت با موفقیت انجام شده
2 : تو این وضعیت به هر دلیلی عملیات پرداخت با خطا روبرو شده.
</span>
</div>
# Log Table
Field Name | Type |Desc   | Default |  PK | Auto Inc.
--- | --- | --- | --- | ---|---
id|int|||*|*
transaction_id|int
result_code|varchar(10)|<span dir="rtl">کدی هستش که بانک در جواب فراخوانی متد verify به ما پاس میده</span>
result_message|varchar(255)|<span dir="rtl">متن پیامی هست که بانک در جواب فراخوانی متد verify به ما پاس میده</span>
log_date|timestamp

<div dir="rtl">
نکته مهم این هست که من دقیقا نمی دونم که تمام بانک ها کدی که برای وضعیت پرداخت به ما برمیگردونه عددی هست یا نه؟ برای همین از نوع کاراکتر گرفتم تا مشکلی پیش نیاد

اگر پیشنهادی هم دارید اعلام کنید تا بررسی بشه

**Comment by m-jch** [comment]
<div dir="rtl">
عالیه
<br>
یک سوال دارم. الان توی درگاه بانک ملت refId و trace_no مشابه هم هستند. درسته؟
<br>
اگر نام فیلد date رو به payment_date یا یک اسم بهتر تبدیل کنیم بهتره و نوعش رو هم باید timestamps باید تبدیل کنیم.
<br>
نباید ما از خطای رخ داده لاگی داشته باشیم؟ مثلا درگاه خراب شده یا کاربر انصراف از پرداخت رو زده؟
</div>

**Comment by Reza1607** [comment]
<div dir="rtl"><span dir="rtl">اسم فیلدها رو تغییر دادم

تو درگاه بانک ملت پارامتر </span>`refId`<span dir="rtl"> با </span>`trace_no`<span dir="rtl"> متفاوت هست
پارامتر <span dir="rtl">`refId`</span> همون کدی هست که ما باید خریدار رو با اون به بانک معرفی کنیم و بانک با استفاده از این کد مبلغ و بقیه اطلاعات لازم رو بدست میاره
و فیلد <span dir="rtl">`tracking_code`</span> هم مقداری که بانک ملت با پارامتر <span dir="rtl">`SaleReferenceId`</span> به ما پاس میده که میشه همون کد پیگیری پرداخت


برای تبدیل نوع به <span dir="rtl">`timestamp`</span> من به خاطر مشکلی که قبلا با  نوع <span dir="rtl">`date`</span> داشتم به ترجیح دادم که از نوع داده <span dir="rtl">`int`</span> استفاده بشه و اگه به نظرم </span>`int`<span dir="rtl"> باشه بهتر هستش

برای لاگ ها هم جدول لاگ رو اضافه کردم

**Comment by m-jch** [comment]
<div dir="rtl">
من فکر میکنم این ساختار میتونه برای ابتدای کار مناسب باشه، و ما هم خیلی زود نمیخوایم نسخه سه رو برای استفاده در محیط production عمومی کنیم، و تا اون زمان احتمالا اگه مشکلی داشته باشه، پیدا میشه.
<br/><br/>
فقط در مورد فیلدهای تاریخ من بازم فکر میکنم باید از نوع timestamp باشه. من هیچ مشکلی تا حالا با فیلدهای timestamp نداشتم.
<br/><br/>
شما اگه بتونی کد پیاده سازی این جدول ها رو در کلاس DatabaseManager پیاده سازی کنید و درخواست pull رو بزنید تا بانک ملت رو با اون سازگار کنیم.

</div>

**Comment by Reza1607** [comment]
<div dir="rtl">
باشه من نوع فیلدها رو تغییر دادم
<span>من فیلد شناسه سفارش رو </span>`order_id`<span dir="rtl"> فراموش کرده بودم که در نظر بگیرم ، که اون رو هم اضافه کردم</span>
</div>
